#!/bin/bash

#check that we have xargs or xjobs installed!
XARGS=$(which xargs)
if [ -x $XARGS ]
then
    git st|grep modified:|awk '{print $NF}'|$XARGS git add
else
    for i in `git st|grep modified:|grep '\.'|awk '{print \$NF}'`;do git add $i; done
fi
